---
apiVersion: v1
kind: Namespace
metadata:
  name: opsight
  labels:
    app.kubernetes.io/name: opsight
    app.kubernetes.io/part-of: opsight-platform
    app.kubernetes.io/managed-by: helm
    environment: staging
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: opsight-production
  labels:
    app.kubernetes.io/name: opsight
    app.kubernetes.io/part-of: opsight-platform
    app.kubernetes.io/managed-by: helm
    environment: production
spec: {} 