{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsight.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsight.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.service.metricsPort }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.backend.service.metricsPort }}
      targetPort: {{ .Values.backend.service.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "opsight.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end -}} 