{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsight.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsight.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.frontend.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "opsight.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end -}} 