{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsight.fullname" . }}-frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsight.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  NODE_ENV: {{ .Values.frontend.env.NODE_ENV | quote }}
  NEXT_PUBLIC_APP_VERSION: {{ .Values.frontend.env.NEXT_PUBLIC_APP_VERSION | quote }}
  NEXT_PUBLIC_ENVIRONMENT: {{ .Values.app.environment | quote }}
  {{- if .Values.frontend.env.NEXT_PUBLIC_API_URL }}
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
  {{- else }}
  NEXT_PUBLIC_API_URL: {{ printf "http://%s-backend:%d" (include "opsight.fullname" .) (.Values.backend.service.port | int) | quote }}
  {{- end }}
{{- end -}} 