apiVersion: v1
kind: Namespace
metadata:
  name: opssight
  labels:
    name: opssight
    app.kubernetes.io/name: opssight
    app.kubernetes.io/component: namespace
    app.kubernetes.io/managed-by: kustomize