---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opssight-backend
  namespace: opssight
  labels:
    app.kubernetes.io/name: opssight
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opssight-frontend
  namespace: opssight
  labels:
    app.kubernetes.io/name: opssight
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false